// Date: 2015/3/4 13:11:39
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.frostcraftsman.gimmickery.model;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelFrostDoll extends ModelBase
{
  //fields
    ModelRenderer head;
    ModelRenderer body;
    ModelRenderer rightarm;
    ModelRenderer leftarm;
    ModelRenderer rightleg;
    ModelRenderer leftleg;
    ModelRenderer teorsionBar;
    ModelRenderer gear1;
    ModelRenderer gear2;
    ModelRenderer gear3;
    ModelRenderer gear4;
    ModelRenderer gear5;
  
  public ModelFrostDoll()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      head = new ModelRenderer(this, 0, 0);
      head.addBox(-3F, -4F, -2F, 4, 4, 4);
      head.setRotationPoint(0F, 0F, 0F);
      head.setTextureSize(64, 32);
      head.mirror = true;
      setRotation(head, 0F, 0F, 0F);
      body = new ModelRenderer(this, 16, 16);
      body.addBox(-4F, 0F, -2F, 6, 12, 4);
      body.setRotationPoint(0F, 0F, 0F);
      body.setTextureSize(64, 32);
      body.mirror = true;
      setRotation(body, 0F, 0F, 0F);
      rightarm = new ModelRenderer(this, 40, 16);
      rightarm.addBox(-1F, -2F, -1F, 2, 10, 2);
      rightarm.setRotationPoint(-5F, 2F, 0F);
      rightarm.setTextureSize(64, 32);
      rightarm.mirror = true;
      setRotation(rightarm, 0F, 0F, 0.2094395F);
      leftarm = new ModelRenderer(this, 40, 16);
      leftarm.addBox(-3F, -2F, -1F, 2, 10, 2);
      leftarm.setRotationPoint(5F, 2F, 0F);
      leftarm.setTextureSize(64, 32);
      leftarm.mirror = true;
      setRotation(leftarm, 0F, 0F, -0.2094395F);
      rightleg = new ModelRenderer(this, 0, 16);
      rightleg.addBox(-2F, 0F, -2F, 2, 12, 2);
      rightleg.setRotationPoint(-2F, 12F, 0F);
      rightleg.setTextureSize(64, 32);
      rightleg.mirror = true;
      setRotation(rightleg, 0F, 0F, 0F);
      leftleg = new ModelRenderer(this, 0, 16);
      leftleg.addBox(-2F, 0F, -2F, 2, 12, 2);
      leftleg.setRotationPoint(2F, 12F, 0F);
      leftleg.setTextureSize(64, 32);
      leftleg.mirror = true;
      setRotation(leftleg, 0F, 0F, 0F);
      teorsionBar = new ModelRenderer(this, 0, 0);
      teorsionBar.addBox(-1.5F, 3F, 2F, 1, 1, 2);
      teorsionBar.setRotationPoint(0F, 0F, 0F);
      teorsionBar.setTextureSize(64, 32);
      teorsionBar.mirror = true;
      setRotation(teorsionBar, 0F, 0F, 0F);
      gear1 = new ModelRenderer(this, 0, 0);
      gear1.addBox(-2F, 2.533333F, 4F, 2, 2, 1);
      gear1.setRotationPoint(0F, 0F, 0F);
      gear1.setTextureSize(64, 32);
      gear1.mirror = true;
      setRotation(gear1, 0F, 0F, 0F);
      gear2 = new ModelRenderer(this, 0, 0);
      gear2.addBox(0F, 3F, 4F, 1, 1, 1);
      gear2.setRotationPoint(0F, 0F, 0F);
      gear2.setTextureSize(64, 32);
      gear2.mirror = true;
      setRotation(gear2, 0F, 0F, 0F);
      gear3 = new ModelRenderer(this, 0, 0);
      gear3.addBox(-1.5F, 1.5F, 4F, 1, 1, 1);
      gear3.setRotationPoint(0F, 0F, 0F);
      gear3.setTextureSize(64, 32);
      gear3.mirror = true;
      setRotation(gear3, 0F, 0F, 0F);
      gear4 = new ModelRenderer(this, 0, 0);
      gear4.addBox(-3F, 3F, 4F, 1, 1, 1);
      gear4.setRotationPoint(0F, 0F, 0F);
      gear4.setTextureSize(64, 32);
      gear4.mirror = true;
      setRotation(gear4, 0F, 0F, 0F);
      gear5 = new ModelRenderer(this, 0, 0);
      gear5.addBox(-1.533333F, 4.5F, 3.966667F, 1, 1, 1);
      gear5.setRotationPoint(0F, 0F, 0F);
      gear5.setTextureSize(64, 32);
      gear5.mirror = true;
      setRotation(gear5, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    head.render(f5);
    body.render(f5);
    rightarm.render(f5);
    leftarm.render(f5);
    rightleg.render(f5);
    leftleg.render(f5);
    teorsionBar.render(f5);
    gear1.render(f5);
    gear2.render(f5);
    gear3.render(f5);
    gear4.render(f5);
    gear5.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5,Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
